const menuBtn = {
  border: 'none',
  borderRadius: '0',
  padding: '0 18px',
  fontWeight: 500,
  cursor: 'pointer',
  fontSize: '16px',
  margin: 0,
  background: 'none',
  color: '#23273a',
  boxShadow: 'none',
  outline: 'none',
  height: '64px',
  display: 'flex',
  alignItems: 'center',
  justifyContent: 'center',
  transition: 'all 0.2s cubic-bezier(.4,0,.2,1)',
};

const featureBtn = {
  border: 'none',
  padding: '0 16px',
  fontWeight: 400,
  cursor: 'pointer',
  fontSize: '14px',
  margin: 0,
  background: 'none',
  color: '#545e70',
  boxShadow: 'none',
  outline: 'none',
  height: '44px',
  display: 'flex',
  alignItems: 'center',
  justifyContent: 'center',
  transition: 'all 0.2s cubic-bezier(.4,0,.2,1)',
};

export const appStyles = {
  appContainer: { width: '100%', height: '100vh', display: 'flex', flexDirection: 'column' },
  navbar: {
    backgroundColor: '#f8f9fa',
    borderBottom: '1px solid #ddd',
    paddingLeft: '20px',
    paddingRight: '0',
    display: 'flex',
    alignItems: 'center',
    height: '64px',
    gap: '24px',
    justifyContent: 'space-between',
  },
  submenu: {
    backgroundColor: '#ecf1f8',
    borderBottom: '1px solid #d0d4dd',
    paddingLeft: '20px',
    paddingRight: '20px',
    display: 'flex',
    alignItems: 'center',
    height: '44px',
    gap: '4px',
    justifyContent: 'flex-start',
  },
  featureBtn,
  featureBtnActive: {
    ...featureBtn,
    background: '#2176ae',
    color: '#fff',
    fontWeight: 400,
    boxShadow: '0 2px 6px rgba(30,34,47,0.08)',
    borderRadius: '0',
  },
  featureBtnInactive: {
    ...featureBtn,
    background: 'transparent',
    color: '#545e70',
  },
  logo: {
    margin: 0,
    fontSize: '28px',
    color: 'black',
    fontWeight: 700,
    display: 'flex',
    alignItems: 'center',
    height: '100%',
    lineHeight: '64px',
  },
  userInfo: {
    display: 'none',
  },
  welcomeText: {
    margin: 0,
    color: 'black',
    fontSize: '16px',
    fontWeight: 400,
    display: 'flex',
    alignItems: 'center',
    height: '100%',
    lineHeight: '64px',
  },
  menuBtn,
  logoutBtn: {
    ...menuBtn,
    background: '#dc3545',
    color: 'white',
    borderRadius: '0',
    minHeight: '40px',
    fontWeight: 500,
    boxShadow: '0 2px 8px rgba(30,34,47,0.10)',
    transition: 'all 0.2s cubic-bezier(.4,0,.2,1)',
    borderLeft: 'none',
    marginLeft: 0,
  },
  mainContent: {
    flex: 1,
    overflowY: 'auto',
    overflowX: 'hidden',
    padding: '0 0 0 0',
    outline: 'none',
    height: '100%',
    minWidth: 0,
    minHeight: '64px',
    letterSpacing: '0.2px',
    display: 'block',
    transition: 'all 0.18s cubic-bezier(.4,0,.2,1)',
    position: 'relative',
  },
  menuBtnActive: {
    background: '#d3d6de',
    color: '#23273a',
    fontWeight: 500,
    border: 'none',
    boxShadow: '0 2px 8px rgba(30,34,47,0.10)',
    zIndex: 1,
    outline: 'none',
  },
  menuBtnInactive: {
    background: '#e3e7ed',
    color: '#23273a',
    fontWeight: 500,
    border: 'none',
    boxShadow: 'none',
    outline: 'none',
  },
  center: { width: '100%', height: '100%', display: 'flex', justifyContent: 'center', alignItems: 'center' }
};
