const menuBtn = {
  border: '1px solid transparent',
  borderRadius: '0',
  padding: '0 18px',
  fontWeight: 500,
  cursor: 'pointer',
  fontSize: '16px',
  margin: 0,
  background: 'none',
  color: '#23273a',
  boxShadow: 'none',
  outline: 'none',
  height: '64px',
  display: 'flex',
  alignItems: 'center',
  justifyContent: 'center',
  transition: 'all 0.2s cubic-bezier(.4,0,.2,1)',
};

const featureBtn = {
  border: 'none',
  padding: '0 16px',
  fontWeight: 400,
  cursor: 'pointer',
  fontSize: '14px',
  margin: 0,
  background: 'none',
  color: '#545e70',
  boxShadow: 'none',
  outline: 'none',
  height: '44px',
  display: 'flex',
  alignItems: 'center',
  justifyContent: 'center',
  transition: 'all 0.2s cubic-bezier(.4,0,.2,1)',
};

export const appStyles = {
  appContainer: {
    width: '100%',
    height: '100vh',
    margin: 0,
    padding: 0,
    display: 'flex',
    flexDirection: 'column',
    background: '#f4f6f8',
    boxSizing: 'border-box',
    overflowX: 'hidden',
  },
  navbar: {
      backgroundColor: '#f8f9fa',
    borderBottom: '1px solid #ddd',
    paddingLeft: '20px',
    paddingRight: '0',
    display: 'flex',
    alignItems: 'center',
    height: '64px',
    gap: '24px',
    justifyContent: 'space-between',
    width: '100%',
    boxSizing: 'border-box',
    position: 'sticky',
    top: 0,
    zIndex: 1000,
  },
  submenu: {
      backgroundColor: '#ecf1f8',
    borderBottom: '1px solid #d0d4dd',
    paddingLeft: '20px',
    paddingRight: '20px',
    display: 'flex',
    alignItems: 'center',
    height: '44px',
    gap: '4px',
    justifyContent: 'flex-start',
  },
  featureBtn,
  featureBtnActive: {
    ...featureBtn,
      backgroundColor: '#2176ae',
    color: '#fff',
    fontWeight: 400,
    boxShadow: '0 2px 6px rgba(30,34,47,0.08)',
    borderRadius: '0',
  },
  featureBtnInactive: {
    ...featureBtn,
      backgroundColor: 'transparent',
    color: '#545e70',
  },
  logo: {
    margin: 0,
    fontSize: '18px',
    color: 'black',
    fontWeight: 700,
    display: 'flex',
    alignItems: 'center',
    height: '100%',
    lineHeight: '64px',
  },
  userInfo: {
    display: 'none',
  },
  welcomeText: {
    margin: 0,
    color: 'black',
    fontSize: '16px',
    fontWeight: 400,
    display: 'flex',
    alignItems: 'center',
    height: '100%',
    lineHeight: '64px',
  },
  menuBtn,
  logoutBtn: {
    ...menuBtn,
    background: 'linear-gradient(135deg, #ff3b30 0%, #d11b1b 100%)',
    color: 'white',
    borderRadius: '0',
    minHeight: '40px',
    fontWeight: 700,
    boxShadow: '0 2px 10px rgba(209, 27, 27, 0.32)',
    transition: 'all 0.2s cubic-bezier(.4,0,.2,1)',
    borderLeft: 'none',
    border: '1px solid rgba(255,255,255,0.18)',
    marginLeft: 0,
  },
  mainContent: {
    flex: 1,
    overflowY: 'auto',
    overflowX: 'hidden',
    padding: '0',
    outline: 'none',
    width: '100%',
    minWidth: 0,
    minHeight: 'calc(100vh - 64px)',
    letterSpacing: '0.2px',
    display: 'block',
    transition: 'all 0.18s cubic-bezier(.4,0,.2,1)',
    position: 'relative',
    boxSizing: 'border-box',
  },
  menuBtnActive: {
    background: '#d3d6de',
    color: '#23273a',
    fontWeight: 500,
    border: '1px solid transparent',
    boxShadow: 'none',
    zIndex: 1,
    outline: 'none',
  },
  menuBtnInactive: {
    background: '#e3e7ed',
    color: '#23273a',
    fontWeight: 500,
    border: '1px solid transparent',
    boxShadow: 'none',
    outline: 'none',
  },
  notificationContainer: {
    position: 'relative',
    display: 'flex',
    alignItems: 'center',
    marginRight: '12px',
  },
  notificationBtn: {
    border: 'none',
    background: 'transparent',
    color: 'black',
    width: '48px',
    height: '48px',
    borderRadius: '10px',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    position: 'relative',
    padding: 0,
    outline: 'none',
    transition: 'background 0.1s ease',
  },
  notificationBtnActive: {
    background: 'transparent',
    color: 'black',
  },
  notificationCount: {
    position: 'absolute',
    top: '6px',
    right: '6px',
    minWidth: '18px',
    height: '18px',
    borderRadius: '9px',
    background: 'black',
    color: 'white',
    fontSize: '11px',
    lineHeight: '18px',
    textAlign: 'center',
    fontWeight: 700,
    padding: '0 4px',
  },
  notificationDot: {
    position: 'absolute',
    top: '8px',
    left: '8px',
    width: '8px',
    height: '8px',
    borderRadius: '50%',
    background: '#ff4d4d',
  },
  notificationPanel: {
    position: 'absolute',
    top: '62px',
    right: 0,
      backgroundColor: 'white',
    border: '1px solid #d0d4dd',
    boxShadow: '0 8px 24px rgba(0,0,0,0.08)',
    borderRadius: '12px',
    minWidth: '300px',
    maxWidth: '320px',
    maxHeight: '360px',
    overflowY: 'auto',
    padding: '10px',
    zIndex: 100,
  },
  notificationHeader: {
    fontSize: '14px',
    fontWeight: 700,
    marginBottom: '10px',
    color: '#23273a',
  },
  notificationItem: {
    padding: '10px 10px 8px 10px',
    borderBottom: '1px solid #d6dadd',
    color: '#23273a',
      backgroundColor: '#f8f9fb',
  },
  notificationItemAlternate: {
    padding: '10px 10px 8px 10px',
    borderBottom: '1px solid #d6dadd',
    color: '#23273a',
      backgroundColor: '#e5ebf1',
  },
  notificationItemNew: {
    padding: '10px 10px 8px 10px',
    borderBottom: '1px solid #d6dadd',
      backgroundColor: '#dde4ea',
    color: '#23273a',
  },
  notificationItemNewAlternate: {
    padding: '10px 10px 8px 10px',
    borderBottom: '1px solid #d6dadd',
      backgroundColor: '#c7d2dd',
    color: '#23273a',
  },
  notificationDismissBtn: {
    background: 'transparent',
    border: 'none',
    color: '#545e70',
    cursor: 'pointer',
    fontSize: '16px',
    lineHeight: '1',
    padding: '0 6px',
    margin: '-4px 0 -4px 8px',
    minWidth: '24px',
    height: '24px',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    outline: 'none',
  },
  notificationText: {
    fontSize: '13px',
    marginBottom: '4px',
  },
  notificationMeta: {
    fontSize: '11px',
    color: '#646f7f',
  },
  notificationEmpty: {
    padding: '16px',
    textAlign: 'center',
    color: '#777',
    fontSize: '13px',
  },
  mobileNavIconButton: {
    background: 'transparent',
    border: 'none',
    cursor: 'pointer',
    width: '48px',
    height: '48px',
    borderRadius: '12px',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: '#23273a',
    padding: 0,
    outline: 'none',
  },
  mobileEdgeRailButton: {
    position: 'fixed',
    top: '64px',
    bottom: 0,
    width: '18px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 80,
    background: 'rgba(21, 26, 39, 0.94)',
    border: '1px solid rgba(255,255,255,0.08)',
    borderRadius: 0,
    boxShadow: 'none',
    cursor: 'pointer',
    padding: 0,
  },
  mobileEdgeRailHandle: {
    width: '32px',
    height: '32px',
    borderRadius: 0,
    background: 'linear-gradient(135deg, #2f4f82 0%, #1b2744 100%)',
    border: '1px solid rgba(255,255,255,0.22)',
    boxShadow: 'none',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: '#fff',
  },
  mobileDrawerBackdrop: {
    position: 'fixed',
    inset: 0,
    backgroundColor: 'rgba(13, 18, 36, 0.45)',
    zIndex: 99,
  },
  mobileDrawer: {
    position: 'fixed',
    top: 0,
    right: 0,
    bottom: 0,
    width: '74vw',
    maxWidth: '320px',
    background: 'linear-gradient(180deg, #20263d 0%, #151a2b 100%)',
    borderLeft: '1px solid rgba(255,255,255,0.08)',
    borderRadius: 0,
    boxShadow: 'none',
    padding: 0,
    boxSizing: 'border-box',
    display: 'flex',
    flexDirection: 'column',
    gap: 0,
    zIndex: 100,
    transform: 'translateX(100%)',
    transition: 'transform 220ms ease-in-out',
    color: '#f8fafc',
  },
  mobileCategoryDrawer: {
    position: 'fixed',
    top: 0,
    left: 0,
    bottom: 0,
    width: '74vw',
    maxWidth: '320px',
    background: 'linear-gradient(180deg, #20263d 0%, #151a2b 100%)',
    borderRight: '1px solid rgba(255,255,255,0.08)',
    borderRadius: 0,
    boxShadow: 'none',
    padding: 0,
    boxSizing: 'border-box',
    display: 'flex',
    flexDirection: 'column',
    gap: 0,
    zIndex: 100,
    transform: 'translateX(-100%)',
    transition: 'transform 220ms ease-in-out',
    color: '#f8fafc',
  },
  mobileAnalysisDrawer: {
    position: 'fixed',
    top: 0,
    right: 0,
    bottom: 0,
    width: '74vw',
    maxWidth: '320px',
    background: 'linear-gradient(180deg, #20263d 0%, #151a2b 100%)',
    borderLeft: '1px solid rgba(255,255,255,0.08)',
    borderRadius: 0,
    boxShadow: 'none',
    padding: '18px 14px',
    boxSizing: 'border-box',
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
    zIndex: 100,
    transform: 'translateX(100%)',
    transition: 'transform 220ms ease-in-out',
    color: '#f8fafc',
  },
  mobileDrawerOpen: {
    transform: 'translateX(0)',
  },
  mobileDrawerCloseButton: {
    alignSelf: 'flex-end',
    background: 'transparent',
    border: 'none',
    color: '#f8fafc',
    fontSize: '26px',
    fontWeight: 700,
    lineHeight: 1,
    cursor: 'pointer',
    padding: '0',
    margin: '-8px -8px 0 0',
  },
  mobileNavTitle: {
    fontSize: '18px',
    fontWeight: 700,
    marginBottom: '10px',
    color: '#f8fafc',
  },
  mobileMenuItem: {
    width: '100%',
    padding: '14px 16px',
    borderRadius: 0,
    border: '1px solid rgba(255,255,255,0.10)',
    backgroundColor: 'rgba(255,255,255,0.04)',
    color: '#f8fafc',
    textAlign: 'left',
    cursor: 'pointer',
    fontSize: '15px',
    fontWeight: 600,
    boxShadow: 'none',
    boxSizing: 'border-box',
  },
  mobileMenuItemActive: {
    backgroundColor: 'rgba(107, 125, 255, 0.16)',
    borderColor: 'rgba(139, 156, 255, 0.28)',
    boxShadow: 'none',
  },
  mobileSubsection: {
    marginTop: '8px',
    paddingTop: '12px',
    borderTop: '1px solid #e0e4ea',
  },
  menuBtnOverlap: {
    marginRight: '-1px',
  },
  center: { width: '100%', height: '100%', display: 'flex', justifyContent: 'center', alignItems: 'center' }
};
