export const styles = {
  container: { padding: 32, maxWidth: 800, margin: '0 auto' },
  header: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 24, color: '#000' },
  title: { fontSize: 28, margin: 0 },
  addButton: { backgroundColor: '#007bff', color: 'white', border: 'none', padding: '10px 20px', borderRadius: 6, cursor: 'pointer', fontSize: 16, transition: 'all 0.2s ease', outline: 'none' },
  loading: { textAlign: 'center', padding: 40, fontSize: 18, color: '#000' },
  form: { backgroundColor: '#f8f9fa', padding: 24, borderRadius: 8, marginBottom: 24, border: '1px solid #ddd' },
  formGroup: { marginBottom: 16 },
  formRow: { display: 'flex', gap: 16 },
  label: { display: 'block', marginBottom: 4, fontWeight: 'bold', color: '#000' },
  input: { width: '100%', padding: 8, border: '1px solid #ddd', borderRadius: 4, fontSize: 16, outline: 'none' },
  select: { width: '100%', padding: 8, border: '1px solid #ddd', borderRadius: 4, fontSize: 16, outline: 'none' },
  checkbox: { marginRight: 8 },
  checkboxLabel: { display: 'flex', alignItems: 'center', fontSize: 16, cursor: 'pointer', color: '#000' },
  checkboxContainer: { display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(150px, 1fr))', gap: '10px', padding: '10px 0' },
  checkboxItem: { display: 'flex', alignItems: 'center', fontSize: 14, cursor: 'pointer', color: '#333' },
  submitButton: { backgroundColor: '#28a745', color: 'white', border: 'none', padding: '12px 24px', borderRadius: 6, cursor: 'pointer', fontSize: 16, width: '100%', transition: 'all 0.2s ease', outline: 'none' },
  budgetsList: { display: 'grid', gap: 16 },
  emptyMessage: { textAlign: 'center', color: '#666', fontSize: 18, padding: 40 },
  budgetCard: { backgroundColor: 'white', border: '1px solid #ddd', borderRadius: 8, padding: 20, boxShadow: '0 2px 4px rgba(0,0,0,0.1)', cursor: 'pointer', transition: 'all 0.25s ease' },
  budgetHeader: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12 },
  categoryName: { margin: 0, fontSize: 20, color: '#333' },
  actions: { display: 'flex', gap: 8 },
  editButton: { backgroundColor: '#ffc107', color: 'black', border: 'none', padding: '6px 12px', borderRadius: 4, cursor: 'pointer', transition: 'all 0.2s ease' },
  deleteButton: { backgroundColor: '#dc3545', color: 'white', border: 'none', padding: '6px 12px', borderRadius: 4, cursor: 'pointer', transition: 'all 0.2s ease' },
  budgetDetails: { marginBottom: 12 },
  period: { margin: 0, color: '#666', fontSize: 14 },
  categoriesSection: { marginBottom: 12, paddingBottom: 12, borderBottom: '1px solid #f0f0f0' },
  categoryBadges: { display: 'flex', flexWrap: 'wrap', gap: '8px', overflow: 'hidden', contain: 'layout paint' },
  categoryBadge: { display: 'inline-flex', alignItems: 'center', justifyContent: 'center', padding: '8px 16px', borderRadius: '20px', fontSize: 14, fontWeight: '500', border: '1.5px solid', cursor: 'pointer', outline: 'none', boxSizing: 'border-box', backfaceVisibility: 'hidden', userSelect: 'none', WebkitUserSelect: 'none', lineHeight: 1, minHeight: '36px' },
  amounts: { marginTop: 12 },
  amountRow: { display: 'flex', justifyContent: 'space-between', marginBottom: 4, fontSize: 16 },
  rolloverNote: { margin: '8px 0 0 0', fontSize: 12, color: '#666', fontStyle: 'italic' },
  progressBar: { height: 8, backgroundColor: '#e9ecef', borderRadius: 4, overflow: 'hidden' },
  progressFill: { height: '100%', transition: 'width 0.3s ease' },
  overlay: {
    position: 'fixed',
    top: 0, left: 0, right: 0, bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 3000
  },
  modal: {
    backgroundColor: 'white',
    borderRadius: '16px',
    padding: '24px',
    width: '90%',
    maxWidth: '380px',
    boxShadow: '0 20px 40px rgba(0,0,0,0.2)'
  },
  confirmBox: { textAlign: 'center', padding: '10px 0' },
  warningIcon: { fontSize: '40px', marginBottom: '10px' },
  confirmActions: { display: 'flex', flexDirection: 'column', gap: '10px', marginTop: '20px' },
  confirmDeleteBtn: {
    padding: '12px',
    backgroundColor: '#dc3545',
    color: 'white',
    border: 'none',
    borderRadius: '8px',
    fontWeight: 'bold',
    cursor: 'pointer',
    transition: 'all 0.2s ease'
  },
  cancelBtn: {
    padding: '12px',
    backgroundColor: '#eee',
    color: '#333',
    border: 'none',
    borderRadius: '8px',
    transition: 'all 0.2s ease',
    fontWeight: 'bold',
    cursor: 'pointer'
  }
};
